# Este es un archivo de configuración de ejemplo para Supabase
# Asegúrate de ajustar los valores según las necesidades específicas de tu proyecto

[global]
project_id = "tkqpqbbljkwsdptcwysk"
app_name = "LaburandoApps"

[db]
port = 5432
shadow_port = 54320
major_version = 15

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://laburando-app-laburandoapps-projects.vercel.app/"
additional_redirect_urls = ["https://laburando-app-laburandoapps-projects.vercel.app/", "https://laburando-app-laburandoapps-projects.vercel.app/**", "https://laburando-*-app-laburandoapps-projects.vercel.app", "https://laburando-*-app-laburandoapps-projects.vercel.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[analytics]
enabled = false
port = 54327
vector_port = 54328