version: '3'
services:
  postgres:
    image: supabase/postgres:14.1.0.34
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: your_password_here

  kong:
    image: kong:2.8.1
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong.yml:ro

  auth:
    image: supabase/gotrue:v2.10.0
    ports:
      - "9999:9999"
    environment:
      GOTRUE_JWT_SECRET: your_jwt_secret_here
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DATABASE_URL: postgres://postgres:your_password_here@postgres:5432/postgres
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9999
      GOTRUE_DISABLE_SIGNUP: "false"

  rest:
    image: postgrest/postgrest:v9.0.0
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:your_password_here@postgres:5432/postgres
      PGRST_JWT_SECRET: your_jwt_secret_here
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon

